{
  	viewer {
    		savingsAccount {
      			id
      			redeemableDeposits {
      				id
              rate
              vehicle
              openDate
              maturityDate
              principal
              redeemedBalance{
                  netAmount
                  yield
                  incomeTax
                  iofTax
                  id
              }
    			}
  		}
  		id
  	}
}
